### ISSUE TITLE
TemplateDoesNotExist

### ISSUE THREAD

**Issue by creimers** [urga/djangocms-slider#1]
I installed djangocms_slideshow as instructed.

If I want to add a slideshow to the content placeholder, I get the following error message:

TemplateDoesNotExist at /de/admin/cms/page/edit-plugin/1/
adminsortable/edit_inline/tabular.html

Admitting that my Django knowledge is limited, I don't quite know what to make of this.
![bildschirmfoto 2014-11-10 um 13 08 28](https://cloud.githubusercontent.com/assets/6090492/4975635/6a4da276-68db-11e4-8da2-ebe7c40fc0f4.png)

**Comment by RubenVW-dev** [comment]
Can you specify more what goes wrong?
The error is only if you load the specific page or is it on any page you load?
Can you check if slideshow_image and slideshow_slideshow tables are in your database?

**Comment by driesdesmet** [comment]
Add 'adminsortable' to your INSTALLED_APPS settings. This wasn't in the readme, so I added it. Django-admin-sortable is a dependancy of this plugin and you need to explicitly add it to your settings if it's not already there. That will make your app look into the templates directory and find the template you got this error on.
